# Generated by Django 2.1.5 on 2021-05-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20181229_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'وعده غذایی', 'verbose_name_plural': 'وعده غذایی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='meals/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='people',
            field=models.IntegerField(verbose_name='نفرات'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='preperation_time',
            field=models.IntegerField(verbose_name='زمان حاظر شدن'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='قیمت'),
        ),
    ]
