# Generated by Django 2.1.5 on 2021-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20190105_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'دریاره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'آشپز', 'verbose_name_plural': 'آشپز'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'چرا ما را انتخوای کنید', 'verbose_name_plural': 'چرا ما را انتخوای کنید'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='bio',
            field=models.TextField(verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to='chef/', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='why_choose_us',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='why_choose_us',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
