# Generated by Django 2.1.5 on 2021-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210513_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.CharField(max_length=100, verbose_name='نعداد '),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(max_length=100, verbose_name='قیمت '),
        ),
    ]
